import type { Product } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Rocket League T-Shirt",
    description: "Black cotton T-shirt with Rocket League logo.",
    price: 19.99,
    currency: "USD",
    image: "/images/rocket-league-tee-1.webp",
    inStock: true,
    rating: 4.5,
    images: [
      "/images/rocket-league-tee-1.webp",
      "/images/rocket-league-tee-2.webp",
      "/images/rocket-league-tee-3.webp",
    ],
  },
  {
    id: "2",
    name: "Gaming Mouse",
    description: "High precision RGB gaming mouse.",
    price: 49.99,
    currency: "USD",
    image: "/images/gaming-mouse-1.webp",
    inStock: false,
    rating: 4.8,
    images: [
      "/images/gaming-mouse-1.webp",
      "/images/gaming-mouse-2.webp",
      "/images/gaming-mouse-3.webp",
    ],
  },
  {
    id: "3",
    name: "Mechanical Keyboard",
    description: "RGB backlit mechanical gaming keyboard.",
    price: 109.99,
    currency: "USD",
    image: "/images/mechanical-keyboard-1.webp",
    inStock: true,
    rating: 4.7,
    images: [
      "/images/mechanical-keyboard-1.webp",
      "/images/mechanical-keyboard-2.webp",
      "/images/mechanical-keyboard-3.webp",
    ],
  },
  {
    id: "4",
    name: "Gaming Headset",
    description: "Over-ear RGB gaming headset with microphone.",
    price: 79.99,
    currency: "USD",
    image: "/images/gaming-headset-1.webp",
    inStock: true,
    rating: 4.6,
    images: [
      "/images/gaming-headset-1.webp",
      "/images/gaming-headset-2.webp",
      "/images/gaming-headset-3.webp",
    ],
  },
  {
    id: "5",
    name: "Wireless Controller",
    description: "Ergonomic wireless controller, Xbox-style layout.",
    price: 59.99,
    currency: "USD",
    image: "/images/controller-1.webp",
    inStock: true,
    rating: 4.4,
    images: [
      "/images/controller-1.webp",
      "/images/controller-2.webp",
      "/images/controller-3.webp",
    ],
  },
  {
    id: "6",
    name: "Gaming Chair",
    description: "Ergonomic reclining chair with adjustable armrests.",
    price: 199.99,
    currency: "USD",
    image: "/images/gaming-chair-1.webp",
    inStock: true,
    rating: 4.3,
    images: [
      "/images/gaming-chair-1.webp",
      "/images/gaming-chair-2.webp",
      "/images/gaming-chair-3.webp",
    ],
  },
  {
    id: "7",
    name: "XL RGB Mousepad",
    description: "Oversized mousepad with glowing RGB edges.",
    price: 39.99,
    currency: "USD",
    image: "/images/mousepad-1.webp",
    inStock: true,
    rating: 4.2,
    images: [
      "/images/mousepad-1.webp",
      "/images/mousepad-2.webp",
      "/images/mousepad-3.webp",
    ],
  },
  {
    id: "8",
    name: "Rocket League Poster",
    description: "High-quality glossy Rocket League wall poster.",
    price: 14.99,
    currency: "USD",
    image: "/images/rocket-league-poster-1.webp",
    inStock: true,
    rating: 4.9,
    images: [
      "/images/rocket-league-poster-1.webp",
      "/images/rocket-league-poster-2.webp",
      "/images/rocket-league-poster-3.webp",
    ],
  },
  // --- Added extra products for pagination ---
  {
    id: "9",
    name: "Gaming Desk",
    description: "Sturdy desk with RGB edge lighting.",
    price: 249.99,
    currency: "USD",
    image: "/images/gaming-desk-1.webp",
    inStock: true,
    rating: 4.3,
    images: [
      "/images/gaming-desk-1.webp",
      "/images/gaming-desk-2.webp",
      "/images/gaming-desk-3.webp",
    ],
  },
  {
    id: "10",
    name: "Streaming Microphone",
    description: "USB condenser mic with pop filter.",
    price: 129.99,
    currency: "USD",
    image: "/images/microphone-1.webp",
    inStock: true,
    rating: 4.6,
    images: [
      "/images/microphone-1.webp",
      "/images/microphone-2.webp",
      "/images/microphone-3.webp",
    ],
  },
  {
    id: "11",
    name: "Webcam",
    description: "1080p HD streaming webcam with wide angle lens.",
    price: 89.99,
    currency: "USD",
    image: "/images/webcam-1.webp",
    inStock: true,
    rating: 4.1,
    images: [
      "/images/webcam-1.webp",
      "/images/webcam-2.webp",
      "/images/webcam-3.webp",
    ],
  },
  {
    id: "12",
    name: "LED Light Panels",
    description: "Modular RGB wall panels for gaming setup.",
    price: 149.99,
    currency: "USD",
    image: "/images/light-panels-1.webp",
    inStock: true,
    rating: 4.5,
    images: [
      "/images/light-panels-1.webp",
      "/images/light-panels-2.webp",
      "/images/light-panels-3.webp",
    ],
  },
  {
    id: "13",
    name: "VR Headset",
    description: "Wireless VR headset with controllers.",
    price: 399.99,
    currency: "USD",
    image: "/images/vr-headset-1.webp",
    inStock: true,
    rating: 4.7,
    images: [
      "/images/vr-headset-1.webp",
      "/images/vr-headset-2.webp",
      "/images/vr-headset-3.webp",
    ],
  },
  {
    id: "14",
    name: "Portable SSD",
    description: "1TB USB-C high-speed gaming SSD.",
    price: 149.99,
    currency: "USD",
    image: "/images/ssd-1.webp",
    inStock: true,
    rating: 4.9,
    images: ["/images/ssd-1.webp", "/images/ssd-2.webp", "/images/ssd-3.webp"],
  },
  {
    id: "15",
    name: "Gamepad Dock",
    description: "Charging dock for up to 4 controllers.",
    price: 39.99,
    currency: "USD",
    image: "/images/gamepad-dock-1.webp",
    inStock: true,
    rating: 4.3,
    images: [
      "/images/gamepad-dock-1.webp",
      "/images/gamepad-dock-2.webp",
      "/images/gamepad-dock-3.webp",
    ],
  },
  {
    id: "16",
    name: "Rocket League Mug",
    description: "Ceramic mug with Rocket League print.",
    price: 12.99,
    currency: "USD",
    image: "/images/rocket-league-mug-1.webp",
    inStock: true,
    rating: 4.4,
    images: [
      "/images/rocket-league-mug-1.webp",
      "/images/rocket-league-mug-2.webp",
      "/images/rocket-league-mug-3.webp",
    ],
  },
];
